CREATE DATABASE ecommerce_analysis;
USE ecommerce_analysis;

CREATE TABLE IF NOT EXISTS ecommerce_dataset(
    product_id INT,
    product_name VARCHAR(50),
    category VARCHAR(50),
    price DECIMAL(10,2),
    units_sold INT,
    rating DECIMAL(3,1),
    in_stock BOOLEAN 
);

-- Dataset preview
SELECT * FROM ecommerce_dataset LIMIT 10;

-- Data Exploration
-- Total Products
SELECT COUNT(*) AS total_products
FROM ecommerce_dataset;

-- Categories present
SELECT DISTINCT category
FROM ecommerce_dataset;
-- Products present
SELECT DISTINCT product_name
FROM ecommerce_dataset;

-- Product Count by Category
SELECT category,
COUNT(*) AS total_products 
FROM ecommerce_dataset
GROUP BY category;

-- Average price by category
SELECT category,
ROUND(AVG(price),2) AS avg_price
FROM ecommerce_dataset
GROUP BY category;

-- Highest rated products
SELECT product_name,
ROUND(AVG(rating),2) AS avg_rating
FROM ecommerce_dataset
GROUP BY product_name
ORDER BY avg_rating DESC
LIMIT 5;

-- Data Cleaning
-- Checking NULL values
SELECT *
FROM ecommerce_dataset
WHERE product_name IS NULL
OR category IS NULL
OR price IS NULL
OR units_sold IS NULL
OR rating IS NULL
OR in_stock IS NULL;

-- Duplicate check 
SELECT product_id,
COUNT(*) AS duplicate_count
FROM ecommerce_dataset
GROUP BY product_id
HAVING duplicate_count > 1;

-- Analysis Queries
-- Top 5 Best selling Products
SELECT product_name,
SUM(units_sold) AS total_sales
FROM ecommerce_dataset
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 5;

-- Sales by Category
SELECT category,
SUM(units_sold) AS total_units
FROM ecommerce_dataset
GROUP BY category;

-- Average Product Rating
SELECT product_name,
ROUND(AVG(rating),2) AS avg_rating
FROM ecommerce_dataset
GROUP BY product_name
ORDER BY avg_rating DESC;

-- Highest Priced Products
SELECT product_name,
price AS highest_price
FROM ecommerce_dataset
ORDER BY price DESC
LIMIT 10;

-- Revenue Generated by Product
SELECT product_name,
ROUND(SUM(price* units_sold),2) AS revenue
FROM ecommerce_dataset
GROUP BY product_name
ORDER BY revenue DESC;

-- Revenue by Category
SELECT category,
ROUND(SUM(price* units_sold),2) AS revenue
FROM ecommerce_dataset
GROUP BY category
ORDER BY revenue DESC;

-- Out of Stock Products
SELECT *
FROM ecommerce_dataset
WHERE in_stock='FALSE';

-- In Stock Products Count
SELECT in_stock,
COUNT(*) AS total
FROM ecommerce_dataset
GROUP BY in_stock;

-- Products with Rating Above 4
SELECT * 
FROM ecommerce_dataset
WHERE rating > 4;

-- Top Revenue Products
SELECT product_name,
ROUND(SUM(price*units_sold),2) AS revenue
FROM ecommerce_dataset
GROUP BY product_name
ORDER BY revenue DESC
LIMIT 5;
